[package]
name = "Hello_Rust_Web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6"}
tokio = {version = "1.48.0", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"] }
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
tower = "0.5.2"